name: PROD

on :
  workflow_dispatch: #Manual trigger

jobs:
  sync-develop-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Force push develop to main
        run: |
          git checkout develop
          git push origin develop:main --force